---
title: "Story 2: Federal Reserve Mandates Over Time"
---

The Federal Reserve bank is an organization that dictates monetary policy
in the United States influencing short term interest rates. The Federal Reserve operates under a _dual mandate_
from Congress, to aiming to achieve price stability and low unemployment. You can read about it here: [Dual Mandate](https://www.stlouisfed.org/in-plain-english/the-fed-and-the-dual-mandate). These seem to be contradictory objectives - see this wikipedia article on the [Phillips Curve](https://en.wikipedia.org/wiki/Phillips_curve). Another good but short news article which focuses on the specific context of recessions is here: [Soft Landing](https://www.npr.org/2022/07/24/1112770581/inflation-recession-soft-landing-rates-jobs-fed).

In 2020, the Federal Reserve implemented a large policy change: instead of targeting a 2\% inflation rate in 
each quarter, it targeted a 2\% inflation rate over time (this is known as _Flexible Average Inflation Targeting_ or 'FAIT'). This meant that if inflation had been under 2\% in
previous quarters, the Fed would target inflation rates above 2\% for a period of time. The motivation for this 
change was the macroeconomic conditions of the 2010s, during which the Phillips Curve did not show the typical 
negative relationship between unemployment rate and inflation rate. In particular, low unemployment in the late 2010s led the Fed to expect a large increase in inflation unless interest rates were increased. These rate 
increases were followed by further declines in unemployment, but problems in other parts of the market forced the 
Fed to reverse its rate increases. The unexpected dynamics of the 2010s motivated the Fed to switch to FAIT. An excellent article written shortly after the adoption of FAIT is [FAIT Accompli](https://www.slowboring.com/p/fait-accompli)

For this data story, you should create a short series of data visualizations telling the story of how the Fed has 
adapted policy to meet its dual mandate and whether those policies (i.e. explicit the pre-FAIT explicit targeting
and FAIT flexible targeting) were successful.


For this story you will need to source the following data for the last 30 years (you can vary this as you think 
is most informative):

- The Consumer Price Index (CPI) (Bureau of Labor Statistics) - note that there are numerous ways to define a CPI, and you can create a custom definition on the BLS page. If you want the standard CPI it is the CPI for all Urban Consumers, or CPI-U. You can find this and other BLS datasets here: [https://data.bls.gov/toppicks?survey=bls](https://data.bls.gov/toppicks?survey=bls). Please remember that inflation is defined as a rate of change of CPI.

- The FED Funds Rate (FRED) (Federal Reserve Board) - This can be found here: [https://fred.stlouisfed.org/series/FEDFUNDS](https://fred.stlouisfed.org/series/FEDFUNDS)

- Unemployment Rate (Bureau of Labor Statistics). I recommend using the seasonally adjusted rate.

- You may find visual frameworks such as the one presented here (describing targeting in the pre-FAIT period) as
useful templates on which to construct your data story: [Chicago Fed Bullseye](https://www.chicagofed.org/research/dual-mandate/dual-mandate)


**Notes:**

1. Use quarto and R or python to compose your report.
2. Remember, the FED raises rates after reviewing the CPI and other data, and unemployment (layoffs) occurs after company operating costs go up.
3. This assignment is due at the end of week four of the semester.
