---
title: "Module 12 - Hierarchical Clustering"
editor: source
---

# Overview and Deliverables

* 11/16: Attend the course meetup at 8:00PM Eastern
* Continue working on [Story 6](../assignments/stories/tbd.qmd), due at the end of this week (Sunday 11/22)

### Readings

1. Wikipedia article on [Hierarchical Clustering](https://en.wikipedia.org/wiki/Hierarchical_clustering)
2. [ggdendro introduction and reference](https://cran.r-project.org/web/packages/ggdendro/vignettes/ggdendro.html)
3. [tidyheatmaps documentation](https://jbengler.github.io/tidyheatmaps/reference/tidyheatmap.html)
4. [Bioinformatics Training and Education Program Tutorial on Hierarchical Clustering](https://bioinformatics.ccr.cancer.gov/docs/data-visualization-with-r/Lesson5_intro_to_ggplot/)
5. For Python: [Seaborn Clustermap](https://seaborn.pydata.org/generated/seaborn.clustermap.html), [scipy.cluster](https://docs.scipy.org/doc/scipy/reference/cluster.html)

### Meetup

Slides: [Meetup 12 - Hierarchical Clustering](../meetups/meetup-12/meetup-12.qmd)

In this meetup we talk about hierarchical clustering, which is an alternative to traditional clustering methods. We discuss the neighbor-joining algorithm for building trees and show how to calculate them in R and visualize them using the ggdendro package. The clustered heatmap is introduced and we show how to customize them using the tidyheatmaps package. Pros and cons of the hierarchical approach are explored.

[Spring 2025 recording](https://youtu.be/Eolp-goYKCc)
