---
title: "Module 9 - Visualizing Models and Uncertainty"
editor: source
---

# Overview and Deliverables

* 10/26: Attend the course meetup at 8:00PM Eastern
* [Story 5](../assignments/stories/tbd.qmd) is assigned this week and due Sunday 11/8 (end of week 10). You will be making models of the (in)famous Ames housing price dataset.

### Readings

1. Kieran Healy - [Chapter 6: Work with models](https://socviz.co/modeling.html#modeling)
2. __Wilke__ - [Chapter 16: Visualizing uncertainty](https://clauswilke.com/dataviz/visualizing-uncertainty.html). While I like this chapter for its in depth discussion of confidence and credible intervals, the material from this chapter is secondary this week.
3. Chapter/Vignette 15 of [Marginal Effects/Model to Meaning](https://marginaleffects.com/bonus/plot.html) (and if you can read chapters 2 and 3 it will pay dividends for you as a data scientist). This book is wonderful and deserves its own course. We are just going to use it for the plotting functions, but the book is important to remember for the next time you wonder what your models mean and how you should (or should not) interpret your fits.
4. The [broom library](https://broom.tidymodels.org/) will also be useful to us.

### Meetup

Slides: [Meetup 9 - Models and Uncertainty (PDF)](../meetups/meetup-9/meetup-9-slides.pdf)

In this meetup we talk about tools to visualize and interpret models. The emphasis is on using plots of model predictions, counterfactual comparisons, and slopes to show the implications of models instead of focusing on the values of coefficients, which we argue are hard to interpret. We go through how to work with model objects using the broom package in R, how to make large numbers of models using purrr and broom, and how to make the most important model visualizations using the marginaleffects package.

[Spring 2025 recording](https://youtu.be/SjsVs5Ee8S4)
