---
title: "Module 1 - Developing a Critical Eye"
editor: source
---

# Overview and Deliverables

* 8/31: Attend the initial course meetup at 8:00PM Eastern
* Introduce yourself on the course Slack
* [Story 1](../assignments/stories/story1.qmd) is assigned this week and due Sunday 9/13 (end of week 2)
* Make sure your software toolkit is set up (see the [software page](../course/software.qmd))

### Learning Objectives

* Understand a data practitioner's role as a storyteller
* Understand the importance of each of the "Who", "What", "Why", "When", and "How" of a data visualization story
* Begin developing a "Critical Eye": the ability to discern poor quality and misleading visualizations from those of high quality

### Readings

* __Fundamentals of Data Visualization__ ([Wilke](https://clauswilke.com/dataviz/)): Chapters 1 and 2
* __Data visualization__ ([Healy](https://socviz.co/01-look-at-data.html)): Preface and Chapter 1 (Why look at data? and What Makes Figures Bad?) 


### Additional Readings


* __Storytelling with Data__: Chapter 1


### Meetup

Slides: [Meetup 1 - Developing a Critical Eye](../meetups/meetup-1/meetup-1.qmd)

In this meetup we show a case study of how a visualization can tell a more powerful message when improved, talk about the course structure, list considerations and tools to use to craft a data story, introduce the neuroscience behind why storytelling is effective, and talk about quality issues for figures.

